// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAET_reMOvTIzA41gVPJTm2ZJ_I6QA3ado',
    appId: '1:100167816991:web:956512e3b10bee1df9822a',
    messagingSenderId: '100167816991',
    projectId: 'radarbeneficios',
    authDomain: 'radarbeneficios.firebaseapp.com',
    storageBucket: 'radarbeneficios.firebasestorage.app',
    measurementId: 'G-7FTELND430',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhMVWxrdi-uj3m8yIFWQPBcmBwpM3_lmo',
    appId: '1:100167816991:android:570f7af7ffd75b08f9822a',
    messagingSenderId: '100167816991',
    projectId: 'radarbeneficios',
    storageBucket: 'radarbeneficios.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3oHbfZ2a9WAbQevhgtMvM5c4o4NB3JJA',
    appId: '1:100167816991:ios:ba7dc324f51f21d1f9822a',
    messagingSenderId: '100167816991',
    projectId: 'radarbeneficios',
    storageBucket: 'radarbeneficios.firebasestorage.app',
    iosBundleId: 'br.com.radarbeneficios.app',
  );
}
