/* Dados inteiramente ilustrativos. Valores monetários em centavos inteiros. */
(function (root) {
  const stores = [
    [
      "magalu",
      "Magalu",
      "Eletrônicos",
      1800,
      "Até 18%",
      "Até 10% para não-correntistas",
      "18% em itens selecionados. 8% nos demais produtos vendidos e entregues pela loja.\nInicie a compra pelo Inter e confira os produtos participantes antes de pagar.",
    ],
    [
      "natura",
      "Natura",
      "Beleza",
      1400,
      "Até 14%",
      "Até 8% para não-correntistas",
      "Oferta para compras elegíveis iniciadas no Inter.\nCupons de outras origens podem não ser cumulativos.",
    ],
    [
      "casas-bahia",
      "Casas Bahia",
      "Casa",
      1000,
      "Até 10%",
      "Até 6% para não-correntistas",
      "Válido para itens vendidos e entregues pela Casas Bahia.\nFrete e serviços não entram no cálculo do benefício.",
    ],
    [
      "netshoes",
      "Netshoes",
      "Esporte",
      900,
      "Até 9%",
      null,
      "Confira a elegibilidade do produto no destino antes de concluir a compra.",
    ],
    [
      "renner",
      "Renner",
      "Moda",
      800,
      "Até 8%",
      null,
      "Compras iniciadas no Shopping Inter, conforme condições da loja.",
    ],
    [
      "petlove",
      "Petlove",
      "Pets",
      700,
      "Até 7%",
      null,
      "Consulte as condições para assinaturas e compras recorrentes no destino.",
    ],
    [
      "cea",
      "C&A",
      "Moda",
      650,
      "Até 6,5%",
      null,
      "Cashback sobre o valor elegível do pedido, após descontos permitidos.",
    ],
    [
      "centauro",
      "Centauro",
      "Esporte",
      600,
      "Até 6%",
      null,
      "O benefício pode variar por categoria e vendedor.",
    ],
    [
      "ponto",
      "Ponto",
      "Eletrônicos",
      500,
      "Até 5%",
      null,
      "Não inclui frete, seguros ou serviços adicionais.",
    ],
    [
      "zattini",
      "Zattini",
      "Moda",
      400,
      "Até 4%",
      null,
      "Confira os termos completos no destino.",
    ],
    [
      "carrefour",
      "Carrefour",
      "Casa",
      300,
      "Até 3%",
      null,
      "Oferta sujeita à elegibilidade do pedido.",
    ],
    [
      "boticario",
      "O Boticário",
      "Beleza",
      0,
      "0%",
      null,
      "Sem cashback nesta medição.",
    ],
    ["extra", "Extra", "Casa", null, "Ofertas disponíveis", null, ""],
    [
      "loja-ausente",
      "Loja acompanhada",
      "Outros",
      null,
      "Sem dado atual",
      null,
      "Loja não encontrada na última consulta completa.",
    ],
  ].map((r, i) => ({
    id: `partner:${r[0]}`,
    domain: "partner",
    slug: r[0],
    name: r[1],
    category: r[2],
    benefit: r[3],
    benefitText: r[4],
    secondary: r[5],
    conditions: r[6],
    active: i !== 13,
    updated: "Hoje, 09:18",
    sourceUrl: "https://shopping.inter.co/",
  }));

  const livelo = [
    ["natura", "Natura", "Beleza", 8, 2, 10, "PROMOTION_CLUB", "Hoje, 23:59"],
    ["netshoes", "Netshoes", "Esporte", 7, 2, 7, "PROMOTION", "Amanhã, 23:59"],
    ["renner", "Renner", "Moda", 6, 1, 8, "PROMOTION_CLUB", "Amanhã, 23:59"],
    ["magalu", "Magalu", "Eletrônicos", 5, 1, 5, "PROMOTION", "Hoje, 23:59"],
    [
      "beleza",
      "Beleza na Web",
      "Beleza",
      5,
      1,
      7,
      "PROMOTION_CLUB",
      "Em 3 dias",
    ],
    ["petlove", "Petlove", "Pets", 4, 1, 6, "PROMOTION_CLUB", "Em 3 dias"],
    ["centauro", "Centauro", "Esporte", 3, 1, 5, "PROMOTION_CLUB", "Em 4 dias"],
    ["riachuelo", "Riachuelo", "Moda", 3, 1, 3, "PROMOTION", "Em 5 dias"],
    [
      "casas-bahia",
      "Casas Bahia",
      "Casa",
      2,
      1,
      4,
      "PROMOTION_CLUB",
      "Em 6 dias",
    ],
    ["ponto", "Ponto", "Eletrônicos", 2, 2, 6, "CLUB", "Em 6 dias"],
    ["decathlon", "Decathlon", "Esporte", 2, 2, 2, "BASE", null],
    ["extra", "Extra", "Casa", 1, 1, 1, "BASE", null],
    ["zattini", "Zattini", "Moda", 1, 1, 1, "BASE", null],
    [
      "sem-pontos",
      "Parceiro sem medição",
      "Outros",
      null,
      null,
      null,
      "UNKNOWN",
      null,
    ],
  ].map((r, i) => ({
    id: `livelo:${r[0]}`,
    domain: "livelo",
    name: r[1],
    category: r[2],
    points: r[3],
    base: r[4],
    club: r[5],
    campaign: r[6],
    validity: r[7],
    endsToday: i === 0 || i === 3,
    validityOrder: i < 4 ? (i === 0 || i === 3 ? 0 : 1) : i,
    active: true,
    updated: "Hoje, 09:10",
    conditions: `Acúmulo em compras iniciadas pelo link da Livelo.\n${r[6] === "CLUB" ? "A pontuação especial é exclusiva para assinantes do Clube. A pontuação comum permanece igual à base." : "Confira produtos participantes, cupons elegíveis e prazo de crédito no regulamento da campanha."}\nFrete, serviços e pedidos cancelados não geram pontos nesta amostra.`,
    sourceUrl: "https://www.livelo.com.br/",
  }));

  const productSeeds = [
    [
      "edge-256",
      "Smartphone Motorola Edge 60 Pro 256 GB",
      "Motorola",
      "Celulares",
      269900,
      299900,
      26990,
      243910,
      1000,
    ],
    [
      "edge-512",
      "Smartphone Motorola Edge 60 Pro 512 GB",
      "Motorola",
      "Celulares",
      319900,
      359900,
      25592,
      294308,
      800,
    ],
    [
      "galaxy",
      "Smartphone Samsung Galaxy A56 128 GB",
      "Samsung",
      "Celulares",
      219900,
      249900,
      17592,
      202308,
      800,
    ],
    [
      "iphone",
      "Smartphone Apple iPhone 16 128 GB",
      "Apple",
      "Celulares",
      489900,
      529900,
      24495,
      465405,
      500,
    ],
    [
      "ideapad",
      "Notebook Lenovo IdeaPad Slim 3 Ryzen 7 16 GB",
      "Lenovo",
      "Notebooks",
      329900,
      369900,
      26392,
      303508,
      800,
    ],
    [
      "aspire",
      "Notebook Acer Aspire 5 Core i5 512 GB SSD",
      "Acer",
      "Notebooks",
      299900,
      329900,
      14995,
      284905,
      500,
    ],
    [
      "tv-lg",
      "Smart TV LG 50 polegadas 4K UHD",
      "LG",
      "TV e vídeo",
      229900,
      269900,
      18392,
      211508,
      800,
    ],
    [
      "tv-samsung",
      "Smart TV Samsung 55 polegadas Crystal UHD",
      "Samsung",
      "TV e vídeo",
      279900,
      309900,
      22392,
      257508,
      800,
    ],
    [
      "geladeira",
      "Geladeira Electrolux Frost Free 400 litros",
      "Electrolux",
      "Casa",
      359900,
      399900,
      17995,
      341905,
      500,
    ],
    [
      "airfryer",
      "Air Fryer Philips Walita 4,1 litros",
      "Philips",
      "Casa",
      39990,
      49990,
      3999,
      35991,
      1000,
    ],
    [
      "fone",
      "Fone de ouvido JBL Tune sem fio",
      "JBL",
      "Áudio",
      24990,
      29990,
      2499,
      22491,
      1000,
    ],
    [
      "monitor",
      "Monitor LG UltraWide 29 polegadas",
      "LG",
      "Monitores",
      109990,
      129990,
      5499,
      104491,
      500,
    ],
  ];
  const direct = ["Casas Bahia", "Ponto"].flatMap((store, s) =>
    productSeeds.map((r, i) => ({
      id: `direct:${s ? "ponto" : "casas-bahia"}:${r[0]}`,
      externalId: r[0],
      domain: "direct",
      name: r[1],
      store,
      brand: r[2],
      category: r[3],
      price: r[4],
      original: r[5],
      cashback: r[6],
      net: r[7],
      benefit: r[8],
      benefitText: `${r[8] / 100}%`,
      installment: "Parcelamento disponível; consulte as condições no Inter.",
      active: true,
      available: true,
      updated: s ? "Hoje, 08:46" : "Hoje, 08:32",
      sourceUrl: "https://shopping.inter.co/",
      specs: [
        "Garantia conforme vendedor",
        "Confira a variante antes de comprar",
      ],
      tags: i < 2 ? ["5G", "Modelo ilustrativo"] : [],
    })),
  );

  const pichau = [
    [
      "Aquila",
      "Ryzen 5 5500",
      "RTX 4060",
      "16 GB",
      "480 GB SSD",
      399990,
      449990,
      470576,
      1500,
    ],
    [
      "Mancer",
      "Ryzen 5 5600",
      "RTX 4060",
      "16 GB",
      "1 TB SSD",
      449990,
      499990,
      529400,
      1000,
    ],
    [
      "Gamer Atlas",
      "Core i5 12400F",
      "RTX 4060 Ti",
      "16 GB",
      "1 TB SSD",
      549990,
      599990,
      647047,
      800,
    ],
    [
      "Gamer Aurora",
      "Ryzen 7 5700X",
      "RTX 4070",
      "32 GB",
      "1 TB SSD",
      749990,
      829990,
      882341,
      1000,
    ],
    [
      "Mancer Thor",
      "Ryzen 5 4600G",
      "Radeon integrada",
      "16 GB",
      "480 GB SSD",
      189990,
      219990,
      223518,
      1400,
    ],
    [
      "Gamer Orion",
      "Ryzen 7 7700",
      "RTX 4070 Super",
      "32 GB",
      "1 TB SSD",
      899990,
      979990,
      1058812,
      800,
    ],
  ].flatMap((r, i) =>
    [0, 1].map((v) => ({
      id: `pichau:${i}-${v}`,
      domain: "pichau",
      externalId: `PCM-${67001 + i * 2 + v}`,
      name: `PC ${r[0]} ${r[1]} com ${r[2]}${v ? " — gabinete branco" : ""}`,
      brand: i === 1 || i === 4 ? "Mancer" : "Pichau",
      category: "PC Gamer",
      cpu: r[1],
      gpu: r[2],
      ram: r[3],
      storage: r[4],
      price: i === 5 && v === 1 ? null : r[5],
      original: r[6],
      cardPrice: r[7],
      discount: r[8],
      discountText: `${r[8] / 100}% de desconto no Pix`,
      installment: "Até 12x no cartão. Consulte juros no destino.",
      available: !(i === 3 && v === 1),
      active: !(i === 5 && v === 1),
      updated: "Hoje, 09:02",
      sourceUrl: "https://www.pichau.com.br/",
      tags: ["Montado", "PC Gamer"],
    })),
  );

  const events = [
    {
      id: "a1",
      itemId: "pichau:0-0",
      domain: "pichau",
      type: "price",
      title: "O preço Pix caiu",
      before: "R$ 4.199,90",
      after: "R$ 3.999,90",
      name: "PC Aquila Ryzen 5 + RTX 4060",
      time: "Hoje, 09:02",
      day: "Hoje",
      read: false,
    },
    {
      id: "a2",
      itemId: "livelo:natura",
      domain: "livelo",
      type: "points",
      title: "Mais pontos na Natura",
      before: "4 pts/R$ 1",
      after: "8 pts/R$ 1",
      name: "Natura",
      time: "Hoje, 09:10",
      day: "Hoje",
      read: false,
    },
    {
      id: "a3",
      itemId: "partner:magalu",
      domain: "partner",
      type: "cashback",
      title: "O cashback mudou",
      before: "Até 12%",
      after: "Até 18%",
      name: "Magalu",
      time: "Hoje, 09:18",
      day: "Hoje",
      read: false,
    },
    {
      id: "a4",
      itemId: "direct:casas-bahia:edge-256",
      domain: "direct",
      type: "price",
      title: "Novo preço registrado",
      before: "R$ 2.799,00",
      after: "R$ 2.699,00",
      name: "Motorola Edge 60 Pro 256 GB",
      time: "Ontem, 20:25",
      day: "Ontem",
      read: true,
    },
  ];
  const collections = { partner: stores, livelo, direct, pichau };
  const history = {};
  Object.values(collections)
    .flat()
    .forEach((item) => {
      if (item.id.endsWith("sem-pontos") || item.price === null) {
        history[item.id] = [];
        return;
      }
      history[item.id] = Array.from(
        { length: item.domain === "livelo" ? 12 : 14 },
        (_, i) => ({
          id: `${item.id}:h${i}`,
          date:
            i === 0
              ? item.updated
              : `${String(18 - Math.floor((i + 1) / 2)).padStart(2, "0")}/09, ${i % 2 ? "14:10" : "09:10"}`,
          price: item.price == null ? null : item.price + (i > 2 ? 20000 : 0),
          cardPrice:
            item.cardPrice == null
              ? null
              : item.cardPrice + (i > 2 ? 20000 : 0),
          points: item.points == null ? null : i > 2 ? item.base : item.points,
          club: item.club == null ? null : i > 2 ? item.base : item.club,
          benefitText: item.benefitText || null,
          status: "Completa",
          available: item.available !== false,
        }),
      );
    });
  const data = {
    collections,
    events,
    history,
    initialFollowed: [
      "partner:magalu",
      "partner:casas-bahia",
      "livelo:natura",
      "livelo:netshoes",
      "direct:casas-bahia:edge-256",
      "pichau:0-0",
    ],
    domains: {
      partner: {
        name: "Sites parceiros",
        source: "Banco Inter",
        kind: "Cashback em lojas",
        icon: "store",
        route: "partners",
      },
      direct: {
        name: "Compre direto",
        source: "Banco Inter",
        kind: "Preços e cashback",
        icon: "bag",
        route: "direct",
      },
      livelo: {
        name: "Livelo",
        source: "Livelo",
        kind: "Pontos por compra",
        icon: "spark",
        route: "livelo",
      },
      pichau: {
        name: "Pichau",
        source: "Pichau",
        kind: "Computadores gamer",
        icon: "desktop",
        route: "pichau",
      },
    },
  };
  root.RadarData = data;
  if (typeof module !== "undefined") module.exports = data;
})(typeof window !== "undefined" ? window : globalThis);
