export const sourceMeta = {
  livelo: { label: "Livelo", color: "#d8ff4f", tone: "signal" },
  cashback: { label: "Inter · Sites parceiros", color: "#75ded4", tone: "info" },
  produtos: { label: "Inter · Compre direto", color: "#b9a7f5", tone: "violet" },
  pichau: { label: "Pichau", color: "#ff8b76", tone: "danger" },
};

export const summaryData = [
  {
    id: "livelo",
    name: "Livelo",
    description: "Pontos atuais por loja acompanhada.",
    value: "8",
    valueLabel: "alertas no retrato",
    status: "Atualizado há 34 min",
    quality: "good",
    action: "Abrir lojas",
    route: "#/livelo",
  },
  {
    id: "cashback",
    name: "Banco Inter",
    description: "Cashback em Sites parceiros e ofertas diretas.",
    value: "24",
    valueLabel: "lojas acompanhadas",
    status: "Atualizado há 1 h",
    quality: "good",
    action: "Abrir Inter",
    route: "#/inter",
  },
  {
    id: "pichau",
    name: "Pichau",
    description: "PC Gamer com preço Pix e cartão separados.",
    value: "1.180",
    valueLabel: "produtos no retrato",
    status: "Atualizado há 3 h",
    quality: "info",
    action: "Abrir catálogo",
    route: "#/pichau",
  },
];

export const liveloStores = [
  {
    id: "livelo-1",
    name: "Casa & Vídeo",
    category: "Casa",
    points: "7",
    base: "3",
    club: "10",
    campaign: "PROMOTION_CLUB",
    validity: "Válido até 28/09",
    description: "Compras elegíveis recebem pontuação promocional no período informado.",
    followed: true,
    alert: true,
  },
  {
    id: "livelo-2",
    name: "Natura",
    category: "Beleza",
    points: "6",
    base: "2",
    club: null,
    campaign: "PROMOTION",
    validity: "Termina hoje",
    description: "A pontuação promocional depende das condições da campanha.",
    followed: true,
    alert: true,
  },
  {
    id: "livelo-3",
    name: "Booking.com",
    category: "Viagens",
    points: "U$ 4",
    base: "U$ 2",
    club: null,
    campaign: "BAU",
    validity: null,
    description: "Sem validade publicada para este retrato.",
    followed: false,
    alert: false,
  },
  {
    id: "livelo-4",
    name: "O Boticário",
    category: "Beleza",
    points: "3",
    base: "3",
    club: "9",
    campaign: "CLUB",
    validity: "Válido até 02/10",
    description: "Assinantes Clube podem receber uma condição diferente da base.",
    followed: false,
    alert: false,
  },
];

export const cashbackStores = [
  {
    id: "cashback-1",
    name: "Magalu",
    benefit: "Até 20%",
    benefitLabel: "cashback",
    client: "Cliente Inter",
    promo: "Oferta principal",
    conditions: "Cashback válido para compras elegíveis iniciadas no Inter. Consulte as regras da loja antes de concluir.",
    secondary: "Até 14% para não correntistas",
    followed: true,
    updated: "há 1 h",
  },
  {
    id: "cashback-2",
    name: "C&A",
    benefit: "12%",
    benefitLabel: "cashback",
    client: "Cliente Inter",
    promo: "Condição ativa",
    conditions: null,
    secondary: null,
    followed: false,
    updated: "há 1 h",
  },
  {
    id: "cashback-3",
    name: "Amazon",
    benefit: "0%",
    benefitLabel: "oferta disponível",
    client: "Cliente Inter",
    promo: null,
    conditions: "O retrato informa uma oferta disponível com valor zero. O Radar não transforma isso em ausência.",
    secondary: null,
    followed: true,
    updated: "há 4 h",
  },
  {
    id: "cashback-4",
    name: "Riachuelo",
    benefit: "—",
    benefitLabel: "cashback não informado",
    client: null,
    promo: null,
    conditions: null,
    secondary: null,
    followed: false,
    updated: "falha recente",
  },
];

export const productItems = [
  {
    id: "product-1",
    store: "Casas Bahia",
    name: "Smartphone Motorola Edge 60 Pro",
    brand: "Motorola",
    category: "Celulares",
    price: "R$ 3.688,89",
    cash: "R$ 147,55",
    net: "R$ 3.541,34",
    availability: "Disponível",
    tags: ["Oferta direta", "12x sem juros"],
    followed: true,
    updated: "há 2 h",
  },
  {
    id: "product-2",
    store: "Ponto",
    name: "Notebook Lenovo IdeaPad 3i",
    brand: "Lenovo",
    category: "Informática",
    price: "R$ 2.799,00",
    cash: "R$ 83,97",
    net: "R$ 2.715,03",
    availability: "Disponível",
    tags: ["Menor preço atual"],
    followed: false,
    updated: "há 2 h",
  },
  {
    id: "product-3",
    store: "Casas Bahia",
    name: "Air Fryer 5,7 L Inox",
    brand: "Electrolux",
    category: "Casa",
    price: "R$ 449,90",
    cash: "R$ 13,49",
    net: "R$ 436,41",
    availability: "Esgotado",
    tags: ["Último retrato válido"],
    followed: false,
    updated: "há 2 h",
  },
  {
    id: "product-4",
    store: "Ponto",
    name: "Fone Bluetooth sem categoria informada",
    brand: null,
    category: null,
    price: "R$ 129,90",
    cash: "—",
    net: "—",
    availability: "Preço disponível",
    tags: [],
    followed: false,
    updated: "há 3 h",
  },
];

export const pichauItems = [
  {
    id: "pichau-1",
    sku: "PCM-67332",
    name: "PC Gamer Ryzen 5 com RTX 4060",
    brand: "Pichau",
    category: "PC Gamer",
    pix: "R$ 5.499,90",
    original: "R$ 6.199,90",
    discount: "11% no Pix",
    card: "R$ 5.999,90",
    installment: "12x de R$ 499,99",
    availability: "Disponível",
    tags: ["Montado", "PC Gamer"],
    followed: true,
    updated: "há 3 h",
  },
  {
    id: "pichau-2",
    sku: "PCM-88421",
    name: "PC Gamer Ryzen 7 sem GPU dedicada",
    brand: "Pichau",
    category: "PC Gamer",
    pix: "R$ 3.299,90",
    original: null,
    discount: null,
    card: "R$ 3.599,90",
    installment: "10x de R$ 359,99",
    availability: "Disponível",
    tags: ["Entrada"],
    followed: false,
    updated: "há 3 h",
  },
  {
    id: "pichau-3",
    sku: "PCM-10203",
    name: "PC Gamer Core i5 — fora do catálogo",
    brand: "Pichau",
    category: "PC Gamer",
    pix: "—",
    original: "R$ 4.199,90",
    discount: null,
    card: "—",
    installment: null,
    availability: "Fora do catálogo",
    tags: ["Histórico preservado"],
    followed: true,
    updated: "último retrato",
  },
];

export const alerts = [
  { id: "alert-1", source: "livelo", title: "Casa & Vídeo mudou a pontuação", copy: "De 3 para 7 pontos por real no retrato atual.", date: "15/09 · 10:42", read: false },
  { id: "alert-2", source: "cashback", title: "Magalu atualizou o cashback", copy: "A oferta principal agora chega a 20% para Cliente Inter.", date: "15/09 · 09:18", read: false },
  { id: "alert-3", source: "produtos", title: "O preço do Edge 60 Pro mudou", copy: "A nova medição mantém a oferta da Casas Bahia disponível.", date: "14/09 · 18:05", read: true },
  { id: "alert-4", source: "pichau", title: "O PC Gamer teve alteração no Pix", copy: "O preço Pix caiu no último snapshot completo.", date: "14/09 · 15:21", read: true },
];

export const categories = {
  root: ["Celulares", "Informática", "Casa", "Beleza", "Pet", "Moda", "Mercado"],
  Casa: ["Eletrodomésticos", "Cozinhas", "Quarto e camas", "Limpeza e climatização"],
  Eletrodomésticos: ["Refrigeração e lavanderia", "Fogões e fornos", "Micro-ondas"],
  "Refrigeração e lavanderia": ["Geladeiras", "Freezers", "Lavadoras"],
  Celulares: ["Smartphones", "Acessórios para celular", "Wearables"],
  Informática: ["Notebooks", "Monitores", "Periféricos"],
  Beleza: ["Cuidados pessoais", "Perfumaria", "Maquiagem"],
  Pet: ["Cães", "Gatos", "Acessórios"],
};

export const historySamples = [
  { date: "15/09/2026 · 10:42", price: "R$ 3.688,89", cash: "R$ 147,55", net: "R$ 3.541,34" },
  { date: "14/09/2026 · 18:05", price: "R$ 3.749,00", cash: "R$ 149,96", net: "R$ 3.599,04" },
  { date: "13/09/2026 · 10:31", price: "R$ 3.699,90", cash: "R$ 110,99", net: "R$ 3.588,91" },
];
